services:
  redis:
    image: redis:alpine
    container_name: weather-redis
    ports:
      - "6379:6379"

  tracker:
    build: ./tracker
    container_name: weather-tracker
    ports:
      - "8082:5002" # חיצוני 8082 -> פנימי 5002
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=5002
    depends_on:
      - redis

  backend:
    build: ./backend
    container_name: weather-backend
    ports:
      - "8080:5000" # חיצוני 8080 -> פנימי 5000
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - TRACKER_URL=http://tracker:5002/track
      - PORT=5000
    depends_on:
      - tracker

  frontend:
    build: ./frontend
    container_name: weather-frontend
    ports:
      - "8081:5001" # חיצוני 8081 -> פנימי 5001
    environment:
      - BACKEND_URL=http://backend:5000
      - PORT=5001
    depends_on:
      - backend
